{"uuid": "5963acb5-1758-4848-9e28-0dc8c41a3215", "children": ["2f4b9aad-3a77-4133-bcc7-4bd2d4370f82"], "befores": [{"name": "_xunit_setup_method_fixture_TestSet", "status": "broken", "statusDetails": {"message": "ValueError: 元素未找到，且不在黑名单中\n", "trace": "  File \"e:\\test_huahua\\venv\\lib\\site-packages\\pluggy\\_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n  File \"e:\\test_huahua\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 1129, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"e:\\test_huahua\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 901, in call_fixture_func\n    fixture_result = next(generator)\n  File \"e:\\test_huahua\\venv\\lib\\site-packages\\_pytest\\python.py\", line 907, in xunit_setup_method_fixture\n    _call_with_optional_argument(func, method)\n  File \"e:\\test_huahua\\venv\\lib\\site-packages\\_pytest\\python.py\", line 788, in _call_with_optional_argument\n    func()\n  File \"E:\\test_huahua\\testcase\\test_set.py\", line 6, in setup\n    self.set = App().start().main().goto_set()\n  File \"E:\\test_huahua\\page\\main.py\", line 41, in goto_set\n    self.steps(\"../data/mine.yaml\", \"goto_set\")\n  File \"E:\\test_huahua\\page\\base_page.py\", line 90, in steps\n    self.find(step[\"by\"], step[\"locator\"]).click()\n  File \"E:\\test_huahua\\page\\handle_black.py\", line 59, in wrapper\n    raise ValueError(\"元素未找到，且不在黑名单中\")\n"}, "start": 1703747959111, "stop": 1703748031214}], "start": 1703747959111, "stop": 1703748031288}